name: "stanford_cars"
description: "Stanford Cars is a dataset of images of various car models."
source: "https://ai.stanford.edu/~jkrause/cars/car_dataset.html"
license: "https://creativecommons.org/licenses/by/4.0/"

annotations:
  provider: "repository"
  data_structure:
    storage_type: "csv"
    identifier_column: "class_id"
    feature_column: "label"
  default_prompt_template: "a photo of a {}."
  prompt_templates:
    - "a photo of a {}."
    - "a photo of the {}."
    - "a photo of my {}."
    - "i love my {}!"
    - "a photo of my dirty {}."
    - "a photo of my clean {}."
    - "a photo of my new {}."
    - "a photo of my old {}."

providers:
  kaggle:
    uri: "jessicali9530/stanford-cars-dataset" # source: https://www.kaggle.com/datasets/jessicali9530/stanford-cars-dataset
    data_type: "image"
    splits:
      - "train"
      - "test"
    data_structure:
      storage_type: "imagefolder"
